import { ArrowLeft, BookOpen, ChevronRight, PanelsTopLeft, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";

const collections = [
  { id: "official", title: "Official Comic", label: "RHODES ISLAND // OFFICIAL", description: "Comic, 4-koma và các ấn phẩm minh họa được phát hành chính thức.", icon: BookOpen, community: false, status: "OFFICIAL RELEASES" },
  { id: "community", title: "Community Manga", label: "COMMUNITY // CREATIONS", description: "Manga, fan comic và series do cộng đồng sáng tác, được tập hợp để khám phá dõi theo.", icon: UsersRound, community: true, status: "COMMUNITY WORKS" },
];

function CollectionCard({ collection }) {
  const Icon = collection.icon;
  const accent = collection.community ? "text-fuchsia-300" : "text-primary";
  return <article className={`relative min-h-[310px] overflow-hidden border bg-[#090b10]/90 p-6 sm:p-8 ${collection.community ? "border-fuchsia-300/25" : "border-primary/25"}`} style={{ clipPath: "polygon(0 0,calc(100% - 20px) 0,100% 20px,100% 100%,20px 100%,0 calc(100% - 20px))" }}><div className={`absolute inset-0 ${collection.community ? "bg-[radial-gradient(circle_at_88%_12%,rgba(232,121,249,.2),transparent_28%),linear-gradient(145deg,#160c19,#100b16_58%,#07090c)]" : "bg-[radial-gradient(circle_at_88%_12%,rgba(117,224,255,.16),transparent_28%),linear-gradient(145deg,#0b1820,#0a0d12_58%,#07090c)]"}`} /><div className="absolute inset-0 opacity-30 [background-image:repeating-linear-gradient(135deg,rgba(255,255,255,.05)_0px,rgba(255,255,255,.05)_1px,transparent_1px,transparent_10px)]" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><div className={`flex h-14 w-14 items-center justify-center border bg-black/20 ${collection.community ? "border-fuchsia-300/35 text-fuchsia-300" : "border-primary/35 text-primary"}`}><Icon size={28} /></div><span className="font-mono-tech text-[.58rem] tracking-[1.7px] text-white/35">COLLECTION_0{collection.id === "official" ? "1" : "2"}</span></div><div className={`mt-11 font-mono-tech text-[.6rem] tracking-[1.9px] ${accent}`}>{collection.label}</div><h2 className="mt-2 font-heading text-3xl font-bold uppercase tracking-[1.4px] text-white">{collection.title}</h2><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">{collection.description}</p><div className="mt-auto flex items-center justify-between border-t border-white/10 pt-5 font-mono-tech text-[.6rem] tracking-[1.5px] text-white/45"><span>{collection.status}</span><ChevronRight size={17} className={accent} /></div></div></article>;
}

export default function ComicManga() {
  return <main className="relative min-h-[calc(100vh-3.5rem)] overflow-hidden bg-[#07090c] text-foreground"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_86%_0%,rgba(232,121,249,.12),transparent_28%),radial-gradient(circle_at_12%_58%,rgba(88,190,226,.1),transparent_25%),linear-gradient(180deg,#0b0a10,#06080b)]" /><div className="pointer-events-none absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] [background-size:42px_42px]" /><div className="relative mx-auto max-w-[1400px] px-4 py-5 sm:px-6 lg:px-10"><header className="border-b border-white/10 pb-8"><Link to="/story" className="inline-flex items-center gap-2 border border-white/15 bg-black/25 px-3 py-2 font-mono-tech text-[.6rem] tracking-[1.5px] text-white/60 transition-colors hover:border-fuchsia-300/55 hover:text-fuchsia-300"><ArrowLeft size={14} /> STORY ARCHIVE</Link><div className="mt-10 font-mono-tech text-[.64rem] tracking-[2.2px] text-fuchsia-300">// VISUAL_STORY_ARCHIVE</div><div className="mt-3 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h1 className="font-heading text-4xl font-bold uppercase tracking-[2px] text-white sm:text-6xl">Comic &amp; Manga</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Kho truyện tranh tập trung các ấn phẩm official và những tác phẩm manga cộng đồng.</p></div><div className="flex items-center gap-2 font-mono-tech text-[.59rem] tracking-[1.5px] text-white/35"><PanelsTopLeft size={14} className="text-fuchsia-300/70" /> 2 COLLECTIONS</div></div></header><section className="grid gap-5 py-8 md:grid-cols-2">{collections.map((collection) => <CollectionCard key={collection.id} collection={collection} />)}</section><footer className="flex items-center gap-3 border-t border-white/10 pt-4 font-mono-tech text-[.58rem] tracking-[1.4px] text-white/35"><PanelsTopLeft size={14} className="text-fuchsia-300/70" /> COMIC &amp; MANGA DATA SOURCE // PENDING CONNECTION</footer></div></main>;
}
