export const PROF_ICON_BASE =
  "https://raw.githubusercontent.com/ArknightsAssets/ArknightsAssets2/refs/heads/cn/assets/dyn/activity/[uc]act1vhalfidle";

export const CLASSES = [
  { value: "PIONEER", label: "Vanguard" },
  { value: "WARRIOR", label: "Guard" },
  { value: "TANK", label: "Defender" },
  { value: "SNIPER", label: "Sniper" },
  { value: "CASTER", label: "Caster" },
  { value: "MEDIC", label: "Medic" },
  { value: "SUPPORT", label: "Supporter" },
  { value: "SPECIAL", label: "Specialist" },
];

export const RARITY_ORDER = [6, 5, 4, 3, 2, 1];

export const PROFESSION_ICON_MAP = {
  PIONEER: "arts/icon/professionlarge/hub/icon_profession_pioneer.png",
  WARRIOR: "arts/icon/professionlarge/hub/icon_profession_warrior.png",
  TANK: "arts/icon/professionlarge/hub/icon_profession_tank.png",
  SNIPER: "arts/icon/professionlarge/hub/icon_profession_sniper.png",
  CASTER: "arts/icon/professionlarge/hub/icon_profession_caster.png",
  MEDIC: "arts/icon/professionlarge/hub/icon_profession_medic.png",
  SUPPORT: "prefabs/depotbuff/depot_buff_item/icon_profession_support.png",
  SPECIAL: "arts/icon/professionlarge/hub/icon_profession_special.png",
};

export const SUBPROF_LABELS = {
  agent: "Agent",
  bearer: "Standard Bearer",
  charger: "Charger",
  counsellor: "Strategist",
  pioneer: "Pioneer",
  tactician: "Tactician",
  artsfghter: "Arts Fighter",
  centurion: "Centurion",
  fearless: "Dreadnought",
  lord: "Lord",
  instructor: "Instructor",
  fighter: "Fighter",
  sword: "Swordmaster",
  musha: "Soloblade",
  librator: "Liberator",
  reaper: "Reaper",
  crusher: "Crusher",
  hammer: "Earthshaker",
  primguard: "Primal Guard",
  mercenary: "Mercenary",
  artsprotector: "Arts Protector",
  duelist: "Duelist",
  fortress: "Fortress",
  guardian: "Guardian",
  primprotector: "Primal Protector",
  protector: "Protector",
  shotprotector: "Sentry Protector",
  unyield: "Juggernaut",
  aoesniper: "Artilleryman",
  bombarder: "Flinger",
  fastshot: "Marksman",
  closerange: "Heavyshooter",
  hunter: "Hunter",
  longrange: "Deadeye",
  loopshooter: "Loopshooter",
  reaperrange: "Spreadshooter",
  siegesniper: "Besieger",
  skybreaker: "Skybreaker",
  blastcaster: "Blast Caster",
  chain: "Chain Caster",
  corecaster: "Core Caster",
  funnel: "Mech-Accord Caster",
  mystic: "Mystic Caster",
  phalanx: "Phalanx Caster",
  primcaster: "Primal Caster",
  soulcaster: "Shaper Caster",
  splashcaster: "Splash Caster",
  chainhealer: "Chain Medic",
  healer: "Therapist Medic",
  incantationmedic: "Incantation Medic",
  physician: "Medic",
  ringhealer: "Multi-target Medic",
  wandermedic: "Wandering Medic",
  bard: "Bard",
  blessing: "Abjurer",
  craftsman: "Artificer",
  ritualist: "Ritualist",
  slower: "Decel Binder",
  summoner: "Summoner",
  underminer: "Hexer",
  alchemist: "Alchemist",
  dollkeeper: "Dollkeeper",
  executor: "Executor",
  geek: "Geek",
  hookmaster: "Hookmaster",
  merchant: "Merchant",
  pusher: "Push Stroker",
  skywalker: "Skyranger",
  stalker: "Ambusher",
  traper: "Trapmaster",
};

export const CLASS_LABELS_I18N = {
  EN: {
    PIONEER: "Vanguard",
    WARRIOR: "Guard",
    TANK: "Defender",
    SNIPER: "Sniper",
    CASTER: "Caster",
    MEDIC: "Medic",
    SUPPORT: "Supporter",
    SPECIAL: "Specialist",
  },
  VN: {
    PIONEER: "Tiên phong",
    WARRIOR: "Cận vệ",
    TANK: "Phòng ngự",
    SNIPER: "Xạ thủ",
    CASTER: "Thuật sư",
    MEDIC: "Y tế",
    SUPPORT: "Hỗ trợ",
    SPECIAL: "Chuyên viên",
  },
};

export const SUBPROF_LABELS_VN_OVERRIDES = {
  agent: "Đặc vụ",
  bearer: "Cờ hiệu",
  charger: "Xung kích",
  counsellor: "Chiến lược gia",
  pioneer: "Tiền tuyến",
  tactician: "Chiến thuật gia",
  artsfghter: "Arts Fighter",
  centurion: "Cường kích",
  fearless: "Dũng sĩ",
  lord: "Lord",
  instructor: "Giáo quan",
  fighter: "Võ sư",
  sword: "Kiếm sư",
  musha: "Kiếm sĩ",
  librator: "Giải phóng",
  reaper: "Liềm sát",
  crusher: "Trọng kiếm",
  hammer: "Địa chấn",
  primguard: "Cận vệ nguyên tố",
  mercenary: "Lính đánh thuê",
  artsprotector: "Arts Protector",
  duelist: "Song đấu",
  fortress: "Pháo binh",
  guardian: "Hộ vệ",
  primprotector: "Primal Protector",
  protector: "Thiết vệ",
  shotprotector: "Cảnh vệ",
  unyield: "Juggernaut",
  aoesniper: "Pháo thủ",
  bombarder: "Phóng kích",
  fastshot: "Tốc xạ",
  closerange: "Trọng xạ",
  hunter: "Thợ săn",
  longrange: "Thiện xạ",
  loopshooter: "Hoàn xạ",
  reaperrange: "Tản xạ",
  siegesniper: "Vây kích",
  skybreaker: "Phá thiên",
  blastcaster: "Blast Caster",
  chain: "Chain Caster",
  corecaster: "Core Caster",
  funnel: "Mech-Accord Caster",
  mystic: "Mystic Caster",
  phalanx: "Phalanx Caster",
  primcaster: "Primal Caster",
  soulcaster: "Shaper Caster",
  splashcaster: "Splash Caster",
  chainhealer: "Liên trị",
  healer: "Liệu dưỡng",
  incantationmedic: "Thuật trị",
  physician: "Bác sĩ",
  ringhealer: "Đa trị",
  wandermedic: "Du y",
  bard: "Phiêu ca",
  blessing: "Hộ pháp",
  craftsman: "Chế tác",
  ritualist: "Vu tế",
  slower: "Hãm tốc",
  summoner: "Triệu hồi",
  underminer: "Nguyền thuật",
  alchemist: "Giả kim thuật",
  dollkeeper: "Thế thân",
  executor: "Hành quyết",
  geek: "Quái kiệt",
  hookmaster: "Kéo",
  merchant: "Thương nhân",
  pusher: "Đẩy",
  skywalker: "Phòng không",
  stalker: "Phục kích",
  traper: "Đặt bẫy",
};

export const SUBPROF_LABELS_I18N = {
  EN: SUBPROF_LABELS,
  VN: { ...SUBPROF_LABELS, ...SUBPROF_LABELS_VN_OVERRIDES },
};
