export const PROF_ICON_BASE =
  "https://raw.githubusercontent.com/ArknightsAssets/ArknightsAssets2/923feb23e98e1b924d9577b6e88d24f2e5a270d8/assets/dyn/arts/ui/[uc]charcommon/dynprofession";

export const CLASSES = [
  { value: "PIONEER", label: "Vanguard" },
  { value: "WARRIOR", label: "Guard" },
  { value: "TANK", label: "Defender" },
  { value: "SNIPER", label: "Sniper" },
  { value: "CASTER", label: "Caster" },
  { value: "MEDIC", label: "Medic" },
  { value: "SUPPORT", label: "Supporter" },
  { value: "SPECIAL", label: "Specialist" },
];

export const RARITY_ORDER = [6, 5, 4, 3, 2, 1];

export const PROFESSION_ICON_MAP = {
  PIONEER: "icon_profession_pioneer.png",
  WARRIOR: "icon_profession_warrior.png",
  TANK: "icon_profession_tank.png",
  SNIPER: "icon_profession_sniper.png",
  CASTER: "icon_profession_caster.png",
  MEDIC: "icon_profession_medic.png",
  SUPPORT: "icon_profession_support.png",
  SPECIAL: "icon_profession_special.png",
};

export const SUBPROF_LABELS = {
  agent: "Agent",
  bearer: "Standard Bearer",
  charger: "Charger",
  counsellor: "Strategist",
  pioneer: "Pioneer",
  tactician: "Tactician",
  artsfghter: "Arts Fighter",
  centurion: "Centurion",
  fearless: "Dreadnought",
  lord: "Lord",
  instructor: "Instructor",
  fighter: "Fighter",
  sword: "Swordmaster",
  musha: "Soloblade",
  librator: "Liberator",
  reaper: "Reaper",
  crusher: "Crusher",
  hammer: "Earthshaker",
  primguard: "Primal Guard",
  mercenary: "Mercenary",
  artsprotector: "Arts Protector",
  duelist: "Duelist",
  fortress: "Fortress",
  guardian: "Guardian",
  primprotector: "Primal Protector",
  protector: "Protector",
  shotprotector: "Sentry Protector",
  unyield: "Juggernaut",
  aoesniper: "Artilleryman",
  bombarder: "Flinger",
  fastshot: "Marksman",
  closerange: "Heavyshooter",
  hunter: "Hunter",
  longrange: "Deadeye",
  loopshooter: "Loopshooter",
  reaperrange: "Spreadshooter",
  siegesniper: "Besieger",
  skybreaker: "Skybreaker",
  blastcaster: "Blast Caster",
  chain: "Chain Caster",
  corecaster: "Core Caster",
  funnel: "Mech-Accord Caster",
  mystic: "Mystic Caster",
  phalanx: "Phalanx Caster",
  primcaster: "Primal Caster",
  soulcaster: "Shaper Caster",
  splashcaster: "Splash Caster",
  chainhealer: "Chain Medic",
  healer: "Therapist Medic",
  incantationmedic: "Incantation Medic",
  physician: "Medic",
  ringhealer: "Multi-target Medic",
  wandermedic: "Wandering Medic",
  bard: "Bard",
  blessing: "Abjurer",
  craftsman: "Artificer",
  ritualist: "Ritualist",
  slower: "Decel Binder",
  summoner: "Summoner",
  underminer: "Hexer",
  alchemist: "Alchemist",
  dollkeeper: "Dollkeeper",
  executor: "Executor",
  geek: "Geek",
  hookmaster: "Hookmaster",
  merchant: "Merchant",
  pusher: "Push Stroker",
  skywalker: "Skyranger",
  stalker: "Ambusher",
  traper: "Trapmaster",
};
